<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Target.Domain\Target.Domain.csproj" />
    <ProjectReference Include="..\Target.Persistence\Target.Persistence.csproj" />
  </ItemGroup>

</Project>
